name: dart_chromecast
version: 0.2.5
description: Cast videos to your ChromeCast device using Dart
homepage: https://github.com/terrabythia/dart_chromecast

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  protobuf: ^2.0.0
  protoc_plugin: ^20.0.0
  http: any
  cli_util: ^0.3.0
  args: any
  xml: any
  logging: ^1.0.1
  multicast_dns: ^0.3.0
